import fs from "node:fs";

type Outputs = Record<string, Record<string, unknown>>;

function readText(p: string): string {
  return fs.readFileSync(p, "utf8");
}

function writeText(p: string, s: string) {
  fs.writeFileSync(p, s, "utf8");
}

function die(msg: string): never {
  console.error(`ERROR: ${msg}`);
  process.exit(1);
}

function getEnv(name: string): string {
  const v = process.env[name];
  if (!v) die(`${name} is required`);
  return v;
}

function main() {
  const projectName = getEnv("PROJECT_NAME");
  const stackName = `CognitoStack-${projectName}-local`;

  const outputsFile = "cdk-outputs.json";
  const envLocalPath = "../.env.local";

  if (!fs.existsSync(outputsFile)) {
    die(
      `outputs file not found: ${outputsFile} (run: cdk deploy --outputs-file ${outputsFile})`
    );
  }

  const outputs = JSON.parse(readText(outputsFile)) as Outputs;

  const stack = outputs[stackName];
  if (!stack) {
    const stacks = Object.keys(outputs);
    die(
      `stack not found: ${stackName}\nAvailable stacks: ${stacks.join(", ")}`
    );
  }

  const poolId = String(stack["CognitoUserPoolId"] ?? "");
  const clientId = String(stack["CognitoUserPoolClientId"] ?? "");

  if (!poolId || !clientId) {
    die(
      `missing outputs in stack: ${stackName}\n` +
        `Need: CognitoUserPoolId, CognitoUserPoolClientId`
    );
  }

  const body = `# autogenerated from ${outputsFile} (${stackName})
COGNITO_USER_POOL_ID=${poolId}
COGNITO_USER_POOL_CLIENT_ID=${clientId}
`;

  writeText(envLocalPath, body);
  console.log(`Wrote ${envLocalPath}`);
}

main();
